### ISSUE TITLE
Setup Git Integration with XCode

### ISSUE THREAD

**Issue by Rule-Book** [Rule-Book/bugs-and-spiders#6]
Integrate git repository with XCode
So that developers can pull collaborator's code directly from git into XCode.

With this, any developer should be able to switch code between branches to load different checkins or revert changes simply using git.

**Comment by Waltbo** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/25408644/202208891-32f88971-d7d3-4908-afd5-a50d65f25aa8.png">
Don't need to do anything for this
